apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: astool
  name: astool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: astool
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        run: astool
    spec:
      containers:
      - image: testacreu2.azurecr.io/astool:v1
        name: astool
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: astool
  name: astool
  namespace: default
spec:
    containers:
    - name: astool
      image: testacreu2.azurecr.io/astool:v1
      command: ["dotnet"]
      args: ["ASTool.dll","--pushpull", "--input", "http://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/manifest", "--minbitrate", "300000", "--maxbitrate", "2000000", "--liveoffset", "10", "--output", "http://channel2-testlivevi-use2.channel.media.azure.net/ingest.isml"]
