apiVersion: 2018-06-01
location: <Region>
name: astoolpullpush.linux-musl
properties:
  containers:
  - name: astool
    properties:
      image: <ACRName>.azurecr.io/astool.linux-musl:v1
      command: ["./ASTool","--pullpush", "--input", "https://<DNSName>/<path>/<live>.ism/manifest", "--minbitrate", "200000", "--maxbitrate", "1810000", "--liveoffset", "10", "--output", "https://<DNSName>/ingest.isml","--counterperiod","300","--tracefile", "/app/astool.service.log" ,"--tracesize" ,"200000" ,"--tracelevel", "warning"]
      resources:
        requests:
          cpu: .4
          memoryInGb: .3          
  osType: Linux
  imageRegistryCredentials:
  - server: <ACRName>.azurecr.io
    username: <AppUserName>
    password: <AppPassword>
tags: null
type: Microsoft.ContainerInstance/containerGroups
