apiVersion: 2018-06-01
location: <Region>
name: astoolpush.linux-musl
properties:
  containers:
  - name: astoolpushlinux-musl
    properties:
      image: <ACRName>.azurecr.io/astoolpush.linux-musl:v1
      command: ["./ASTool","--push", "--input", "/app/outputvideo/audiovideo.ism", "--output", "https://<DNSName>/ingest.isml", "--loop", "0"]
      resources:
        requests:
          cpu: .4
          memoryInGb: .3
  osType: Linux
  imageRegistryCredentials:
  - server: <ACRName>.azurecr.io
    username: <AppUserName>
    password: <AppPassword>
tags: null
type: Microsoft.ContainerInstance/containerGroups
