apiVersion: apps/v1
kind: Deployment
metadata:
  name: astoolpushlinux
spec:
  selector:
    matchLabels:
      run: astoolpushlinux
  replicas: 1
  template:
    metadata:
      labels:
        run: astoolpushlinux
    spec:
      containers:
      - name: astoolpushlinux
        image: <ACRName>.azurecr.io/astoolpush.linux:v1
        command: ["./ASTool","--push", "--input", "/app/outputvideo/audiovideo.ism", "--output", "https://<DNSName>/ingest.isml", "--loop", "0"]
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            cpu: .4
            memory: 300Mi
