apiVersion: apps/v1
kind: Deployment
metadata:
  name: astoolpullpushlinux
spec:
  selector:
    matchLabels:
      run: astoolpullpushlinux
  replicas: 1
  template:
    metadata:
      labels:
        run: astoolpullpushlinux
    spec:
      containers:
      - name: astoolpullpushlinux
        image: <ACRName>.azurecr.io/astool.linux:v1
        command: ["./ASTool","--pullpush", "--input", "https://<DNSName>/<path>/<live>.ism/manifest", "--minbitrate", "200000", "--maxbitrate", "1810000", "--liveoffset", "10", "--output", "https://<DNSName>/ingest.isml","--counterperiod","300","--tracefile", "/app/astool.service.log" ,"--tracesize" ,"200000" ,"--tracelevel", "warning"]
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            cpu: .4
            memory: 300Mi
