apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: astoolpullpush
  name: astoolpullpush
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: astoolpullpush
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        run: astoolpullpush
    spec:
      containers:
      - image: testacreu2.azurecr.io/astool:v1
        name: astoolpullpush
        command: ["dotnet","ASTool.dll","--pullpush", "--input", "http://channel1-testlivevi-use2.channel.media.azure.net/preview.isml/manifest", "--minbitrate", "300000", "--maxbitrate", "2000000", "--liveoffset", "10", "--output", "http://channel2-testlivevi-use2.channel.media.azure.net/ingest.isml"]
        ports:
        - containerPort: 80
          protocol: TCP
        resources: 
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: astoolpullpush
  name: astoolpullpush
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30759
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: astoolpullpush
  sessionAffinity: None
  type: LoadBalancer
