apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: astool
  name: astool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: astool
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        run: astool
    spec:
      containers:
      - image: <AzureContainerRegistryName>.azurecr.io/astool:v1
        name: astool
        ports:
        - containerPort: 80
          protocol: TCP
        resources: 
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: astool
  name: astool
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30756
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: astool
  sessionAffinity: None
  type: LoadBalancer
